"""Send an auto-reply email via SMTP."""

import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


def send_reply(
    smtp_host: str,
    smtp_port: int,
    smtp_user: str,
    smtp_password: str,
    to_address: str,
    subject: str,
    body: str,
) -> None:
    """Send a plain-text auto-reply email.

    Parameters
    ----------
    smtp_host / smtp_port:
        SMTP server connection details (SSL on port 465).
    smtp_user / smtp_password:
        Login credentials for the SMTP account.
    to_address:
        Recipient email address (the original sender).
    subject:
        Subject line for the reply (will be prefixed with ``Re:`` if missing).
    body:
        Plain-text reply body generated by the LLM.
    """
    if not subject.lower().startswith("re:"):
        subject = f"Re: {subject}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = to_address
    msg["Auto-Submitted"] = "auto-replied"
    msg["X-Auto-Reply"] = "yes"

    msg.attach(MIMEText(body, "plain", "utf-8"))

    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(smtp_host, smtp_port, context=context) as server:
        server.login(smtp_user, smtp_password)
        server.sendmail(smtp_user, to_address, msg.as_string())
